vich_uploader:
    db_driver: orm

    mappings:
       photos:
           uri_prefix: /images/photos_sejours
           upload_destination: '%kernel.project_dir%/public/images/photos_sejours'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
